### ISSUE TITLE
Can we modify cron expression for another timezone?

### ISSUE THREAD

**Issue by jrphub** [jmrozanec/cron-utils-examples#3]
I need something like below:

> newCronExpression = convert (localCronExpresn,fromLocalTZ, "UTC")

Is it possible using cron-utils?

Let me give an example:

My local timezone is IST i.e. GMT+5.30.

Current local time is: 11:20 AM.

I want a job to run in 45 min of every hour.

So, my cron expression: 45 \* \* \* *

Hence I am expecting my job to run after 25 min ( as starting time is 11:45 AM)

but my job is running as per UTC, because of oozie.

Current time in UTC : 05:50 AM

As per cron expression 45 \* \* * , the starting time will be 06:45 AM at GMT.

So, the job will be actually started after 55 min.

> Expected : After 25 min
> 
> Actual : After 55 min

So, 

> if I am converting my local cron expression 45 *\* \* \*  to 15 \* \* \* \* at GMT, then actual waiting period will be same as expected.

**Comment by jmrozanec** [comment]
@jrphub sounds like a nice feature. We can add it to the backlog - should be easy to implement. Feel free to take over the task - I will be glad to accept a pull request. Thank you for the idea!

**Comment by jmrozanec** [comment]
@jrphub we are migrating this issue to [cron-utils](https://github.com/jmrozanec/cron-utils) main project, in order to handle it there! Thanks!
